### ISSUE TITLE
Doesn't build with template-haskell-2.11.0.0 on GHC-7.8.4

### ISSUE THREAD

**Issue by ozgurakgun** [nick8325/quickcheck#101]
Similar to dreixel/generic-deriving#41, QuickCheck doesn't build with template-haskell-2.11.0.0 on GHC-7.8.4 (and GHC-7.10.3). Cabal produces install plans which attempt to do so.

I will provide a simple cabal file to reproduce the issue.

**Comment by ozgurakgun** [comment]
[Here](https://gist.github.com/ozgurakgun/123288528a6679ddf89d3637a45d099d) is the cabal file.

**Comment by ozgurakgun** [comment]
One simple "solution" is to explicitly depend on the main supported version of `template-haskell`, like here: https://github.com/dreixel/generic-deriving/pull/42/files

I am happy to prepare a PR if you prefer this, put please keep in mind that the solution `generic-deriving` guys adopted was different.

**Comment by phadej** [comment]
IIRC this was fixed recently. On mobile, so cannot point the exact commit

**Comment by ozgurakgun** [comment]
@phadej thanks for the heads up, I just checked and I can see https://github.com/nick8325/quickcheck/commit/17db27a6346934313fe55914a1a9120ea6acef59 and https://github.com/nick8325/quickcheck/commit/442c3cf52a1ae937840f5780f0b91cf387f0b412. Any plans for a new minor release?

**Comment by nick8325** [comment]
There, I released a new version!

**Comment by ozgurakgun** [comment]
Thanks @nick8325 for the quick response!
