### ISSUE TITLE
Replace Boolean with ad-hoc type

### ISSUE THREAD

**Issue by Icelandjack** [nick8325/quickcheck#102]
Congratulations on the release

[This commit](https://github.com/nick8325/quickcheck/commit/1195c21606da0abd254ebbb8128b50f39bdbf1d3) adds a Boolean but it is unclear what is being tested when I see `not b`, why not use an ad-hoc type instead? I need help coming up with a name though :)

```haskell
data HaveIBeenShrunk = UnShrunken | Shrunken

data Honey_I = Didn'tShrinkTheKids | ShrunkTheKids
```

**Comment by nick8325** [comment]
Hi! I fixed this just now, so we have `Shrunk` and `NotShrunk` instead.
