### ISSUE TITLE
dependency on text and build times

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#118]
Apparently `QuickCheck` now transitively depends on `text` for GHC < 8. This increases build times on Travis by a couple of minutes for every project that uses `QuickCheck`. Insane!

Any chance that we can get rid of that dependency again?

(see also discussion https://github.com/nick8325/quickcheck/issues/80)

**Comment by phadej** [comment]
@sol This is a compromise between providing uniform API over a range of compilers, or having smaller build times.

I'd say, use dependency caching on Travis.

**Comment by sol** [comment]
With GHC 7.10.2:

```
$ time cabal install QuickCheckg
real    2m10.603s
user    2m31.212s
sys     0m5.100s
```


```
$ time cabal install QuickCheck-2.8.2
real    0m40.412s
user    0m42.380s
sys     0m1.820s

**Comment by sol** [comment]
The build time more tripled for GHC < 8. For me, personally, this is not a compromise I am willing to take.

For `QuickCheck` as a dependency of `hspec` I have not yet decided how to deal with this.

**Comment by sol** [comment]
Here are the numbers for `hspec`:

```
$ time cabal install hspec
real    2m26.978s
user    3m7.448s
sys     0m8.552s
```

```
$ time cabal install hspec QuickCheck-2.8.2
real    1m0.904s
user    1m23.644s
sys     0m5.208s
```

**Comment by sol** [comment]
I put a lot of effort into making `hspec` as lightweight as possible. I think from a user's perspective this is desirable, as you don't want the testing framework to add significantly to your build time.

`QuickCheck-2.9` increases the build time for `hspec` by x 2.5.

@nick8325 any chance we can address this.

**Comment by hvr** [comment]
@sol 

> This increases build times on Travis by a couple of minutes for every project that uses `QuickCheck`

While I don't understand yet the specifics of requiring a `text` dependency at all (as I didn't have time yet to look into the discussions leading up to this), I'd like to point out that your specific Travis concern is addressed by `cabal new-build`-based travis scripts, such as generated by  https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs which make use of Travis' caching feature for caching cabal's new nix-style artifact store between travis invocations. Before that, popular packages like `text` with non-neglectable build-times which tend to be part of almost every install-plan were indeed a nuisance in Travis scripts...

**Comment by nick8325** [comment]
Hi,

I think the culprit is the `semigroups` package, which has a whole load of dependencies. We provide `Arbitrary` instances for `Data.List.NonEmpty`, which lives in `base` on GHC 8 - but it's not included with older GHCs but is part of `semigroups` instead, hence the extra dependency.

@sol, how would it be if I added a flag to QuickCheck to disable this and similar dependencies? We could call it `-flight` or something like that. Obviously, your users would need to put it in their Travis files. I'm worried about removing the dependency unconditionally because it seems likely to break users of QuickCheck.

**Comment by nick8325** [comment]
I've added an `-flight` flag which reduces QuickCheck to the following dependencies (plus those which are supplied with GHC):

```
transformers
primitive
tf-random
```

It's not an ideal solution, but it seems to me that simply failing to provide many instances on older GHC versions would create much bigger headaches.

**Comment by hvr** [comment]
@nick8325 Fwiw, `text` going to be bundled with GHC starting with GHC 8.4
