### ISSUE TITLE
Tuple instances for Testable

### ISSUE THREAD

**Issue by Icelandjack** [nick8325/quickcheck#124]
Are there any fun `Testable` instances missing?

Saw some instances for `Testable` [here](https://github.com/mokus0/junkbox/blob/151014bbef9db2b9205209df66c418d6d58b0d9e/Haskell/Experiments/EqTestable.hs#L6)

``` haskell
instance (Eq a, a ~ a') => Testable (a, a') where
  property :: (a, a) -> Property
  property (a, a') = property (a == a')
```

``` haskell
instance (Eq a, Show a, a ~ a') => Testable (a, a') where
  property :: (a, a) -> Property
  property = uncurry (===)
```

or what ever semantics make sense, this is taken from [`checkers`](https://hackage.haskell.org/package/checkers-0.4.6/docs/src/Test-QuickCheck-Checkers.html):

``` haskell
instance Testable a => Testable [a] where
  property :: [a] -> Property
  property []    = property True
  property props = property $ \n -> props !! (n `mod` len)
    where len = length props

instance (Testable a, Testable b) => Testable (a,b) where
  property :: (a, b) -> Property
  property = uncurry (.&.)
```

**Comment by Icelandjack** [comment]
```haskell
instance Testable () where
  property :: () -> Property
  property () = property True

instance Testable a => Testable (IO a) where
  property :: IO a -> Property
  property = monadicIO . run
```

**Comment by nick8325** [comment]
The ones for tuples and lists look very eccentric, I think it would be better to write the properties explicitly there.

The "Exceptional Testing" one is an interesting idea, maybe I will add that...

**Comment by sol** [comment]
@Icelandjack For "Exceptional testing" you may want to take a look at my package [quickcheck-io](https://hackage.haskell.org/package/quickcheck-io).  In the context of `hspec` you can use it like so.

```haskell
import Test.Hspec
import Test.QuickCheck

main :: IO ()
main = hspec $ do
  describe "reverse" $ do
    it "is inverse to itself" $ do
      property $ \xs -> do
        (reverse . reverse) xs `shouldBe` (xs :: [Int])
        
  describe "readFile" $ do
    it "reads the content of a file" $ do
      property $ \xs -> do
        writeFile "foo" xs
        readFile "foo" `shouldReturn` xs
```
NB: Both `usafePreformaIO` and `error` / `undefined` are problematic (no exception ordering guarantees).  You really, really want to use `ioProperty` and `throwIO` instead!
