### ISSUE TITLE
Make types more precise / generalise 

### ISSUE THREAD

**Issue by Icelandjack** [nick8325/quickcheck#133]
Some functions should only accept [non-empty lists](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-List-NonEmpty.html), now that `NonEmpty` is in *base* it may be worth codifying this in the types:

```haskell
oneof           :: NonEmpty (Gen a)      -> Gen a
frequency       :: NonEmpty (Int, Gen a) -> Gen a  
elements        :: NonEmpty a            -> Gen a 
growingElements :: NonEmpty a            -> Gen a 
```

or generate non-empty lists

```haskell
listOf1 :: Gen a -> Gen (NonEmpty a) 
```
or using [`Foldable1`](https://hackage.haskell.org/package/semigroupoids-5.1/docs/Data-Semigroup-Foldable.html) (which is not in *base* yet)

```haskell
oneof           :: Foldable1 f => f (Gen a)      -> Gen a
frequency       :: Foldable1 f => f (Int, Gen a) -> Gen a
elements        :: Foldable1 f => f a            -> Gen a
growingElements :: Foldable1 f => f a            -> Gen a
```

or using the traditional `Foldable`, retaining the partiality but being compatible with current uses: 

```haskell
oneof           :: Foldable f => f (Gen a)      -> Gen a
frequency       :: Foldable f => f (Int, Gen a) -> Gen a
elements        :: Foldable f => f a            -> Gen a
growingElements :: Foldable f => f a            -> Gen a
```

Googling `"elements toList" QuickCheck` gives us [a](http://stackoverflow.com/a/35529208/165806) [few](https://github.com/paolino/burraco/blob/master/Contesto.hs#L108) [examples](https://github.com/haskell/cabal/blob/master/Cabal/tests/UnitTests/Distribution/Compat/Graph.hs#L58). This does **not** mean that every generalisation makes sense, I always list more ideas than fewer.

----

Other things may make sense

```haskell
infiniteList' :: Arbitrary a => Gen (Stream a) 
```

there is also [`fmap index infiniteList'`](https://hackage.haskell.org/package/adjunctions-4.3/docs/Data-Functor-Rep.html#v:index) of type `Arbitrary a => Gen (Natural -> a)` given a

```haskell
instance Representable Stream where
  type Rep Stream = Numeric.Natural.Natural
```

**Comment by Icelandjack** [comment]
Does the need for `NonEmptyList` change at all given `NonEmpty`?

**Comment by nick8325** [comment]
This would break an awful lot of code. I'm not really convinced that there is any need for it: avoiding partial functions is useful because it prevents runtime errors, but here the errors can only occur during testing, when we are trying to provoke errors anyway.

We need to keep `NonEmptyList` because people use it. With `NonEmpty`, there are two ways to generate a non-empty list, but I don't see that as a problem - if your program uses `NonEmpty` then you can generate values of that type, but if it uses normal lists with an invariant then using `NonEmptyList` is more natural.

**Comment by Icelandjack** [comment]
The primary usefulness would be for documenting, not preventing errors as you note.

Using `Foldable` wouldn't break much code, except the rare inference.

Future: With Liquid Haskell non-emptiness could be specified without changing data structures.
