### ISSUE TITLE
monadicIO ignores results

### ISSUE THREAD

**Issue by nh2** [nick8325/quickcheck#134]
`monadicIO :: PropertyM IO a -> Property` this discards the `a`.

That can be dangerous, consider e.g.:

```haskell
myprop :: Property
myprop = monadicIO $ do
  ...
  return (a == b)
```

The above compiles, but it doesn't do what you think it does, because it discards what you thought was the check (`a == b`).

Wouldn't a better signature be `monadicIO :: PropertyM IO () -> Property`?

**Comment by nh2** [comment]
I put a fix in https://github.com/nick8325/quickcheck/pull/135.

**Comment by nick8325** [comment]
Thanks!

**Comment by nick8325** [comment]
Actually, since `()` recently became an instance of `Testable`, we should be able to give `monadicIO` the type `Testable a => PropertyM IO a -> Property`, which will do what you expect.
