### ISSUE TITLE
Using ‘QuickCheck’ to verify an expression doesn't fail

### ISSUE THREAD

**Issue by Icelandjack** [nick8325/quickcheck#143]
I don't know if something like this exists already, quite often I use QuickCheck to verify that something never fails:

```haskell
>>> quickCheck (\(xs::[Int]) -> let a = map head (group xs) in a == a)
+++ OK, passed 100 tests.
```

Would this be useful (with a more polished implementation)

```haskell
doesn'tFail :: NFData a => a -> Property
doesn'tFail a = deepseq a (property True)

>>> quickCheck (doesn'tFail . map head . group @Int)
+++ OK, passed 100 tests.
```

**Comment by thumphries** [comment]
I would use this if it were available. I often write similar properties.

(A better name would be nice)

**Comment by nick8325** [comment]
Perhaps something like (untested):

```
total :: Eq a => a -> Bool
total x = (x == x) `seq` True
```

This would let us write:

```
prop_NonEmptyGroups :: Eq a => [a] -> Bool
prop_NonEmptyGroups xs = all total (group xs)
```

Not so keen on using `NFData` as it pulls in a dependency on `deepseq` and makes it a bit less convenient to use (as there is more likely to be an `Eq` instance than an `NFData` instance for your type). Would we lose anything in practice by using `Eq` instead?

**Comment by phadej** [comment]
you assume that `Eq` is structural, i.e. walks thru whole data structure. I'm not sure whether this is good.

I'd rather introduce a manual flag `deepseq` which is on by default, if you want to have "light" dependencies option.

**Comment by RyanGlScott** [comment]
Furthermore, `deepseq` is bundled with GHC these days. `QuickCheck` already depends on `random`/`tf-random`, which depend on `time`, which depends on `deepseq`, so `deepseq` is already a transitive dependency of `QuickCheck`.

**Comment by nick8325** [comment]
Yes, on second thoughts it makes more sense to use `deepseq`, especially as `NFData` is easy to derive nowadays.
