### ISSUE TITLE
suchThatNot / suchThatMaybeNot

### ISSUE THREAD

**Issue by Icelandjack** [nick8325/quickcheck#146]
Functions that I've found useful, the first one anyway

```haskell
suchThatNot :: Gen a -> (a -> Bool) -> Gen a
suchThatNot gen f = suchThat gen (not . f)

suchThatMaybeNot :: Gen a -> (a -> Bool) -> Gen (Maybe a)
suchThatMaybeNot gen f = suchThatMaybe gen (not . f)
```

**Comment by nick8325** [comment]
Hmm, it seems a lot to have _four_ different variants of `suchThat`. I wonder if the cognitive overhead of remembering them all is worth it?

**Comment by MaximilianAlgehed** [comment]
It's been 7 years... Let's close this.
