### ISSUE TITLE
quickCheck on once property behaves weird

### ISSUE THREAD

**Issue by onixie** [nick8325/quickcheck#157]
try 
```haskell
main = do
    quickCheck $ once True
    quickCheck True
```

In latest version 2.9.2, the result is
> +++ OK, passed 100 tests.
> +++ OK, passed 1 tests.

while in version <2.9, the result is 
> +++ OK, passed 1 tests.
> +++ OK, passed 1 tests.

BTW, In #113, I see there is a patch to make `Gen` monad test repeatedly.
In the first quickCheck call, `once ` turns `Bool` into `Property` which just contains a `Gen` monad.

**Comment by nick8325** [comment]
Thanks!
