### ISSUE TITLE
mapMaybe :: (a -> Maybe b) -> Gen a -> Gen b

### ISSUE THREAD

**Issue by sjakobi** [nick8325/quickcheck#159]
I'm looking for a function with the above type. What's the best way to construct this function and could it possibly be exported from QuickCheck?

**Comment by Lysxia** [comment]
One way is `\f -> untilJust . fmap f`, where [`untilJust` comes from monad-loops](http://hackage.haskell.org/package/monad-loops-0.4.3/docs/src/Control-Monad-Loops.html#untilJust).

**Comment by nick8325** [comment]
I would do it like this:

```
mapMaybe f x = fmap fromJust (fmap f x `suchThat` isJust)
```

Actually I would use a slightly different combinator instead:

```
fromMaybe :: Gen (Maybe a) -> Gen a
fromMaybe x = fmap fromJust (x `suchThat` isJust)
```

P.S. you should use `suchThat` instead of `untilJust`, because `suchThat` takes care of gradually increasing the size if it fails to generate any test data matching the predicate.

**Comment by sjakobi** [comment]
Thanks guys! Does this look sufficiently non-trivial and useful that it should be included in QuickCheck?

**Comment by nick8325** [comment]
I could definitely imagine adding `fromMaybe`, since it's a bit fiddly and uses a partial function.

Probably not `mapMaybe`, as it can be implemented using `fromMaybe` and `fmap`.

**Comment by phadej** [comment]
`mapMaybe` is the name for such functions: https://www.stackage.org/lts-8.8/hoogle?q=mapMaybe

```haskell
mapMaybe :: (a -> Maybe b) -> [a] -> [b]
mapMaybe :: (a -> Maybe b) -> Map k a -> Map k b
mapMaybe :: Monad m => (a -> Maybe b) -> Conduit a m b
mapMaybe :: Monad m => (a -> Maybe b) -> Stream (Of a) m r -> Stream (Of b) m r
mapMaybe :: Witherable t => mapMaybe :: (a -> Maybe b) -> t a -> t b
```

to list a few.

**Comment by nick8325** [comment]
OK, then it makes sense to add `mapMaybe`. @phadej, do you know if there is a standard name for `fromMaybe`? I can only find `catMaybes`, which doesn't make sense as a name for `Gen`.

**Comment by edmundnoble** [comment]
AFAIK it's also known as `mapFilter` in Scala, in https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/FunctorFilter.scala.

**Comment by nick8325** [comment]
I gave it the name `suchThatMap` because `mapMaybe` might well give QuickCheck users name conflicts.
