### ISSUE TITLE
Result is not updated when shrinking

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#168]
This is true specifically for `theException` and `reason`.
### Steps to reproduce:
```haskell
import Control.Exception
import Control.Monad
import Test.QuickCheck

prop :: Int -> Property
prop n = ioProperty $ do
  when (n > 50) $ do
    throwIO (ErrorCall $ "don't like " ++ show n)
  return True

main :: IO ()
main = do
  r <- quickCheckResult prop
  putStr "theException: "
  print (theException r)
  putStr "reasoe: "
  print (reason r)
```
When I run this program, I see the following output:
```
*** Failed! Exception: 'don't like 51' (after 77 tests and 3 shrinks):    
51
theException: Just don't like 62
reason: "Exception: 'don't like 62'"
```
The couterexample is `51`, but `theException` and `reason` indicate the first value the property failed with before shrinking, `61`.

**Comment by sol** [comment]
@nick8325 thanks a lot for the fix!  Any ETA for Hackage?

**Comment by nick8325** [comment]
As soon as I get time to put a release together - in the next few days, I hope.
