### ISSUE TITLE
Remove Testable instance for ()?

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#173]
Given c51eaaf5d553c19ec82464491ab423bc3aaf8225 it may not be useful anymore?

**Comment by nick8325** [comment]
It's now used by `Test.QuickCheck.Monadic`, see #134.

I think it is still somewhat useful anyway as it allows you to convert an `IO ()` into a `Property` without having to stick a `return True` at the end.

**Comment by sol** [comment]
Ok, cool. Closing.
