### ISSUE TITLE
Always provide the seed in Result

### ISSUE THREAD

**Issue by feuerbach** [nick8325/quickcheck#175]
Hi,

@NovaDenizen [makes the case](https://github.com/feuerbach/tasty/issues/141) that it is sometimes useful to have the seed for passing tests.

They filed it as an issue/PR for tasty, but this needs to be addressed in QuickCheck first of all.

Would it be possible to add the seed to all constructors of the Result type?

**Comment by sol** [comment]
> this needs to be addressed in QuickCheck first of all

I think there is a pretty easy workaround: Use `newQCGen` to generate the *seed* yourself, then pass it to `quickCheckWithResult` when running a property.  That way you have access to the used seed, even if the property succeeds.

N.B.: I'm not saying that I'm opposed to this change, just that I don't think it's necessary for https://github.com/feuerbach/tasty/issues/141.

**Comment by feuerbach** [comment]
Thanks for the comment — this is the approach taken in [the PR](https://github.com/feuerbach/tasty/pull/143) I got, but I think I was confused about it. Will reconsider.

**Comment by feuerbach** [comment]
I went ahead with @NovaDenizen's and @sol's suggestion, so feel free to close this.

**Comment by nick8325** [comment]
OK, I'll close this if it's not wanted any more.
