### ISSUE TITLE
[PDF] Functional Pearl: Ode on a Random Urn

### ISSUE THREAD

**Issue by Icelandjack** [nick8325/quickcheck#178]
This isn't an issue, just a heads up: The paper [*Functional Pearl: Ode on a Random Urn*](http://www.cis.upenn.edu/~llamp/pdf/urns.pdf) proposes a new interface to `frequency`, where it takes an **Urn** data structure instead of a list of pairs

```haskell 
frequency :: Urn (Gen a) -> Gen a
```

Hope it's of interest

**Comment by MaximilianAlgehed** [comment]
I'm going to go ahead and close this as an issue as there hasn't been any fruitful discussion about this in 7 years and the link is unfortunately dead (thanks UPenn!)
