### ISSUE TITLE
Weird output from `verbose`?

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#183]
Here is an example:
```
ghci> import Test.QuickCheck
ghci> quickCheck $ verbose $ \x -> x /= (2 :: Int)
Passed:  
0

Passed: 
1

Passed:  
-2

Passed:  
0

Passed:  
0

Passed:  
4

Failed:  
2

*** Failed! Passed:                       
0

Passed:                                       
1

Falsifiable (after 7 tests):                  
2
```

Specifically, I'm surprised by what I see after the `***`.  I would expect:

```
*** Failed! Falsifiable (after 7 tests):                  
2
```

instead.

As I understand it this happens due to shrinking.  Not sure if we want to fix this.

**Comment by nick8325** [comment]
Right, it prints out "*** Failed!" as soon as the first test case fails, then starts shrinking (which produces more messages).

I wonder what it should do in this case. Maybe leave the "*** Failed!" message until the end?
