### ISSUE TITLE
Consider using `splitmix` instead of `tf-random`

### ISSUE THREAD

**Issue by phadej** [nick8325/quickcheck#184]
Honestly, I don't know if there is huge benefit. `splitmix` is faster than `tf-random`, and based on dieharder tests is as good PRNG as `tf-random`. I open this issue to raise awareness.

**Comment by moodmosaic** [comment]
FWIW, we're using `splitmix` in [Hedgehog](https://github.com/hedgehogqa) from the beginning. The core of [this](https://github.com/nkartashov/SplitMix) SplitMix implementation is in C, so we decided to port it from scratch from the [paper](https://dl.acm.org/citation.cfm?id=2660195). Have a look in the [Seed](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/hedgehog/src/Hedgehog/Internal/Seed.hs) module, if that helps.

/cc @jystic

**Comment by sol** [comment]
> `splitmix` is faster than `tf-random`

I would be interested in numbers / profiling results that confirm that the RNG is a bottle neck for QuickCheck performance.

**Comment by phadej** [comment]
@sol, it most likely isn't :)

**Comment by jystic** [comment]
One of the main reasons we went for `splitmix` in Hedgehog was because it was easy to make a pure Haskell implementation, which makes porting to other languages and things like Eta and GHCJS easier. Of course this isn't that much of a concern for QuickCheck as both Eta and GHCJS have the necessary foreign implementation for `tf-random` already.

**Comment by epogrebnyak** [comment]
To me it looks still there is a reason to replace `tf-random` as it does not install at all on my machine. https://github.com/nick8325/quickcheck/issues/244

**Comment by nick8325** [comment]
It would certainly be easy to switch over. Maybe it would be worth it to get rid of the C dependency?

My only worry is that the dieharder tests don't test splitting (AFAIK), and QuickCheck does a whole lot of splitting. I did try to come up with some tests for splitting a few months ago though and it seems that `splitmix` passes them (while `random` fails). They're not intended to be exhaustive tests but at least `splitmix` seems a lot better than `random` in that respect.

**Comment by idontgetoutmuch** [comment]
A little coda: some splitting test results for `splitmix` are available here: https://github.com/tweag/random-quality/tree/master/results
