### ISSUE TITLE
Question: How to interpret non-discrete number of shrinks as reported by QuickCheck >= 2.11?

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#196]
Steps to reproduce:
```
ghci> quickCheck $ \ (x :: Int) (y :: Int) -> (x == 0 && y == 1) ==> False
*** Failed! Falsifiable (after 1 test and 0.1 shrinks):  
0
1
```

Not sure if this is a bug? But looks fishy!

**Comment by sol** [comment]
For completeness, this is a regression introduced with `2.11`.

**Comment by sol** [comment]
Trying other stuff:
```
> quickCheck ( < 10)
*** Failed! Falsifiable (after 12 tests and 1.4 shrinks):  
10
```

Apparently this is how it is now.  How should I interpret e.g. `1.4 shrinks`?

**Comment by nick8325** [comment]
Ah, whoops.. 1.4 means 1 shrink and 4 unsuccessful shrink attempts, but it is only supposed to be used during shrinking. I'll fix it.

**Comment by nick8325** [comment]
Should be fixed now!

**Comment by nick8325** [comment]
Oh, now it says "1 shrinks". Bleargh.

**Comment by nick8325** [comment]
Should be finally fixed now in 44379d9e.

**Comment by sol** [comment]
@nick8325 Thanks a lot!

I'm not going to support `2.11`, `2.11.1` and `2.11.2` in `hspec`.  Nick, how about deprecating these versions on Hackage?

**Comment by nick8325** [comment]
Ah, good idea - done!
