### ISSUE TITLE
Exception: Negative exponent

### ISSUE THREAD

**Issue by lehins** [nick8325/quickcheck#221]
`arbitrarySizedBoundedIntegral` is subject to integer overflow on the exponent with very large size resulting in an exception:

```haskell
λ> sample (resize maxBound (arbitrarySizedBoundedIntegral :: Gen Int8))
*** Exception: Negative exponent
λ> sample (resize maxBound (arbitrarySizedBoundedIntegral :: Gen Int))
*** Exception: Negative exponent
```

Naturally it also applies to `arbitrary`:
```haskell
λ> sample (resize maxBound (arbitrary :: Gen Int16))
*** Exception: Negative exponent
```

But interestingly, not for `arbitrary :: Gen Int`:
```haskell
λ> sample (resize maxBound (arbitrary :: Gen Int))
-8901454996576912029
...
```

**Comment by nick8325** [comment]
This is a bug - but note that `resize n arbitrarySizedBoundIntegral` generates a number which has roughly `n/2` bits, so you are asking for a number of magnitude approximately `2^2^63`, too big to store in memory.

The following code, for example, does not terminate in any reasonable time on my machine:

```
sample (resize 100000000 (arbitrarySizedBoundedIntegral :: Gen Int))
```

Conceivably `arbitrarySizedBoundedIntegral` should degenerate to producing a number uniformly at random in the entire range if the size parameter is too big.

**Comment by lehins** [comment]
Absolutely, this bug didn't affect me in any way, I just stumbled upon in accidentally and wanted to bring it up.

It's interesting that it does take so long time. I wouldn't expect arbitrary to be that different between such similar types as `Int64` and `Int`, for example, but now I see they are vastly different, since latter uses `arbitrarySizedIntegral`.
```
λ> sample (resize 100000000 (arbitrary :: Gen Int))
68874167
90702690
2149224
-94048992
-68372244
-93246366
-900265
57087928
-54013792
38808494
-18168140
```
which is not only much faster, but also produces different values than:
```
λ> sample (resize 100000000 (arbitrary :: Gen Int64))
4648166734344221159
60614165824252870
-4241411235894547869
4205517746206895489
-4479430771808140916
3177455876649316288
7378471222686933039
-4910524224426007078
6101030690408434938
-8183134933725921389
-6122839710755642091
```

**Comment by nick8325** [comment]
Right, the `Int` generator is a bit different in that it does not try to span the whole range (unless you use `Large Int`) - a size parameter of `n` means to generate integers between `-n` and `n`. This is because `arbitrary :: Gen Int` is often used for example to generate the size of a data structure, where large values would be inappropriate.

Anyway, I've fixed the bug now so both your examples should run equally fast.
