### ISSUE TITLE
NonEmpty

### ISSUE THREAD

**Issue by andrewthad** [nick8325/quickcheck#225]
Data.List.NonEmpty has been in `base` since 8.0. May I add an instance for this type? It would only be available when building against a sufficiently new `base`.

**Comment by phadej** [comment]
We left it on purpose. It's in http://hackage.haskell.org/package/quickcheck-instances

**Comment by andrewthad** [comment]
Ah, that makes sense.

**Comment by kindaro** [comment]
I am disappointed by this decision. Types added to `base` are supposed to be safe to use everywhere, [even in libraries where slim dependencies are a requirement][1]. Alas!

[1]: https://github.com/haskell/bytestring/pull/364#discussion_r653272585
