### ISSUE TITLE
instance Testable Maybe

### ISSUE THREAD

**Issue by amigalemming** [nick8325/quickcheck#243]
How about that instance:
~~~~
instance (Testable prop) => Testable (Maybe prop) where
  property Nothing = property rejected
  property (Just prop) = property prop
~~~~
?

Reason: I have a `Gen` that cannot always produce something, thus it has type `Gen (Maybe a)`. I want to turn `Nothing` into `Discard` when it is finally converted to `Property`. I find `discard` too much of a hack.

Related: #124

**Comment by nick8325** [comment]
I think this is a sensible idea.
