### ISSUE TITLE
Pass at Least Once

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#248]
I've been looking through the docs and have not been able to find a function that tests if a property passes at least one time.

Does this exist?

**Comment by nick8325** [comment]
There's nothing that directly does this, but you can get a similar effect by negating the property and then using `expectFailure`.

For example, instead of

```
prop_sort_is_idempotent :: [Int] -> Property
prop_sort_is_idempotent xs = passesOnce (sort xs === xs)
```

you can do

```
prop_sort_is_idempotent :: [Int] -> Property
prop_sort_is_idempotent xs = expectFailure (sort xs =/= xs)
```

which will also print out a test case where `sort xs == xs`.

**Comment by BebeSparkelSparkel** [comment]
@nick8325 That's a way to come at it, thank you for the suggestion.
I think I'll try testing it a different way that conforms more to the standard way of testing to keep things understandable.
