### ISSUE TITLE
cover outside of ==> doesn't do what I expect

### ISSUE THREAD

**Issue by nh2** [nick8325/quickcheck#25]
```haskell
import Test.QuickCheck

main = quickCheck $
  forAll arbitrary $ \b ->
    cover b 100 "b is True" $
      b ==> True
```

I would expect this to tell me something like `b is true onl 50% of the time`, but I get `OK, passed 100 tests`.

It seems odd to me that the inner `==>` can sneak around the outer `cover`.

If I had written

```haskell
import Test.QuickCheck

main = quickCheck $
  forAll arbitrary $ \b ->
    b ==>
      cover b 100 "b is True" $
        True
```

then that output would be expected, but in my case above `cover` comes first, so it surprised me.

Is this intended?

If so, could we make it clear in the documentation, maybe even this exact example?

**Comment by nick8325** [comment]
Yes, this is expected behaviour - ```cover``` and related functions only count successful (i.e. not discarded or failing) tests. I will add a note to the documentation.

**Comment by nick8325** [comment]
Sorry, forgot to close this bug - this is documented now.
