### ISSUE TITLE
Way to write `Function Void` instance.

### ISSUE THREAD

**Issue by phadej** [nick8325/quickcheck#257]
It would be trivial instance:

```haskell
-- | All @'Void' -> a@ are 'absurd'.
instance Function Void where
    function _ = Nil
```

but `:->` constructors aren't exposed from anywhere.

Should they be, from some internal module?

**Comment by nick8325** [comment]
This instance seems like a good idea.

I don't think there's a need to export the definition `:->` as `functionMap` can always be used to define new instances, as long as there are instances for sums, products, `()` and `Void`.

**Comment by phadej** [comment]
But `Void` isn't in old `base`s. That's the problem. Is adding

```haskell
functionVoid :: a :-> c
functionVoid = Nil
```

be ok?

Then I can add `Function Void` for all supported GHCs and `base` into `quickcheck-instances`.

**Comment by nick8325** [comment]
Sorry for the slow reply.

I'd rather not commit to making `Nil` have the type `a :-> b` for all time. Could we make `functionVoid` take an extra argument that witnesses that the type is void, something like:

```
functionVoid :: (forall b. a -> b) -> a :-> c
functionVoid _ = Nil
```

You would then call it as `functionVoid absurd`. It won't make it impossible for people to use `functionVoid` at non-Void types, but it might make them think twice.
