### ISSUE TITLE
frequency sometimes throws an undocumented exception when the sum of the weights of the input list is non-positive

### ISSUE THREAD

**Issue by Berengal** [nick8325/quickcheck#259]
How to reproduce:
```
λ> generate (frequency [(0, return 1)])
1
λ> generate (frequency [(0, return 1)])
*** Exception: QuickCheck.pick used with empty list
CallStack (from HasCallStack):
  error, called at ./Test/QuickCheck/Gen.hs:197:15 in QuickCheck-2.12.6.1-CG92sgzQynB255SN47n2RX:Test.QuickCheck.Gen
```
It took me longer than it should have to discover the error in my list of frequencies because of the unhelpful error.

This should at least have its own error message, maybe also document the need for positive weights even though it's fairly obvious.

**Comment by nick8325** [comment]
Agree, this is a poor error message.
