### ISSUE TITLE
Make a release.

### ISSUE THREAD

**Issue by phadej** [nick8325/quickcheck#264]
The few latests PR would be very valuable for myself, when released. Could they be released, or is there something holding that? I'd like to help, if I can.

Thanks in advance.

**Comment by nick8325** [comment]
No particular reason not to release them, I just hadn't got around to it yet. I'll do it now.

**Comment by nick8325** [comment]
Done!

**Comment by phadej** [comment]
Thanks, I uploaded [`quickcheck-instances-0.3.22`](https://hackage.haskell.org/package/quickcheck-instances-0.3.22) with `Void` instances.
