### ISSUE TITLE
Assuring exhaustiveness of Arbitrary instances

### ISSUE THREAD

**Issue by sjakobi** [nick8325/quickcheck#267]
I have a large sum type that often gets new constructors. I want to be sure that whenever I add a new constructor, I also update the `Arbitrary` instance to generate the new constructor.

There is [a StackOverflow question](https://stackoverflow.com/questions/25535616/quickcheck-how-to-use-exhaustiveness-checker-to-prevent-forgotten-constructors) offering some ad-hoc solutions for this problem. It's from 2014 though, so I'm wondering what the recommended solution is today.

**Comment by Lysxia** [comment]
Shameless plug: generic-random requires you to specify a weight for every constructor (disclaimer: I'm the author, and there are a few other packages in the same space on Hackage).

**Comment by sjakobi** [comment]
Props for the lovely docs, @Lysxia! :+1: I'll give `generic-random` a try.

Maybe `QuickCheck` should even recommend `generic-random` somewhere?

> there are a few other packages in the same space on Hackage

Can you give me some pointers?

**Comment by Lysxia** [comment]
The alternatives I know of only implement uniform distributions (which makes them that much simpler to their benefit):

- TH: https://hackage.haskell.org/package/quickcheck-arbitrary-template-0.2.1.0
- Generics: https://hackage.haskell.org/package/generic-arbitrary-0.1.0

**Comment by sjakobi** [comment]
I'm very happy with `generic-random` so far! :) 

 [Here](https://github.com/dhall-lang/dhall-haskell/blob/d08ccfb384906bc4aff0087e8766037ccf3394ac/dhall/tests/Dhall/Test/QuickCheck.hs#L231-L326) is the `Arbitrary` instance that I needed it for.

I've also made [an answer](https://stackoverflow.com/a/58572336/1013393) using `generic-random` to the SO question from above.

Thank you @Lysxia for the great support! :+1:
