### ISSUE TITLE
`shrink` and `shrinkDecimal` do not work with negative numbers.

### ISSUE THREAD

**Issue by kindaro** [nick8325/quickcheck#268]
Consider how negative integral numbers are shrunk:

    λ shrinkIntegral 100
    [0,50,75,88,94,97,99]
    λ shrinkIntegral (-100)
    [100,0,-50,-75,-88,-94,-97,-99]

Now see how fractional numbers are:

    λ shrink 1.23
    [1.0,0.0,1.2,0.0,0.6,0.9,1.1,0.0,0.62,0.93,1.08,1.16,1.2,1.22]
    λ shrinkDecimal  (1.23)
    [1.0,0.0,1.2,0.0,0.6,0.9,1.1,0.0,0.62,0.93,1.08,1.16,1.2,1.22]
    λ shrink (-1.23)
    [0.0]
    λ shrinkDecimal  (-1.23)
    [0.0]

I think this is wrong. Negative and positive numbers are equally rightful members of a number
ring, both in its additive and multiplicative aspect. They should be treated evenly.

**Comment by nick8325** [comment]
Fixed. Thanks for reporting the bug!
