### ISSUE TITLE
Fun with lifted type

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#270]
Is is possible to used `Fun` with a lifted type like `Proxy#`?

**Comment by Lysxia** [comment]
A function `Proxy# a -> r` is the same as a value `r`, so you can 
generate an `r` directly.

**Comment by BebeSparkelSparkel** [comment]
If I am passing `Proxy# a -> r` as an argument would I have to use unsafeCoerce#

**Comment by BebeSparkelSparkel** [comment]
I think I'm going to just stick with the traditional `Data.Proxy.Proxy` instead of Proxy#

**Comment by Lysxia** [comment]
A function `myFunction :: (Proxy# a -> R) -> X` that you want to test 
can be wrapped as a function `R -> X`:

```
myFunction' :: R -> X
myFunction' r = myFunction (\_ -> r)
```
