### ISSUE TITLE
within not triggering failure

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#276]
`within` does not cause the test to fail when applied before `quickCheckWith` but works when applied after.

```haskell
fit "within" $
    quickCheckWith stdArgs $
    \(s :: String) -> within 1 $ s `shouldBe` s
```

```text
*** Failed! Timeout (after 22 tests):
    within

Finished in 0.0051 seconds
1 example, 0 failures

Test suite passed
```

This may be an hspec issue but it seems to happen from QuickCheck function ordering.

**Comment by BebeSparkelSparkel** [comment]
Without `quickCheckWith` modifying the test `within` fails properly

```haskell
fit "within" $
    property $ \(s :: String) -> within 1 $ s `shouldBe` s
```

**Comment by phadej** [comment]
Can you provide a reproduce case without depending on `hspec`, i.e. using only `QuickCheck`?

**Comment by sol** [comment]
@BebeSparkelSparkel `quickCheckWith` is not what you want to use here.  Look at https://hackage.haskell.org/package/hspec-2.7.1/docs/Test-Hspec-QuickCheck.html if you want to modify QuickCheck args.

I don't plan to elaborate on this, but in short, `quickCheckWith` is of type `IO ()` and does not throw and exception on failure.  There is no sensible way for Hspec to discover the test outcome if you use `quickCheckWith`.

**Comment by BebeSparkelSparkel** [comment]
@sol I understand now. Thanks
