### ISSUE TITLE
Functor ((:->) a) Poor Performance

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#277]
The following has very poor performance

```haskell
fit "QuickCheck profile" $ property $
  \( applyFun -> g :: Int -> [[Int]]
   , applyFun -> h :: [[Int]] -> Int
   , x
   ) -> do
     h (g (x)) `shouldBe` (h . g $ x)\
```

[parse-it-test.prof.txt](https://github.com/nick8325/quickcheck/files/3831581/parse-it-test.prof.txt)

**Comment by phadej** [comment]
I wouldn't say it's `fmap` is slow. My initial guess is that `Fun [[Int]] Int` is quite big structure, when applied to `[[Int]]` which is quadratic in `size` (~100 lists of ~100 element lists).

**Comment by BebeSparkelSparkel** [comment]
Would you consider 100^2 large?

**Comment by BebeSparkelSparkel** [comment]
Seems like 10,000 or even 100,000 should be a reasonable amount of data to test with.

**Comment by phadej** [comment]
well, 10000 elements * 100 tests (which I suspect is default) can make test run for a half a second, which isn't long time.

I suspect that doubling `maxSize` (from default 100 to 200) would make test run take roughly 4 times the time.

**Comment by BebeSparkelSparkel** [comment]
Ok, I'll cut down the test sizes except for pushs.
Thanks
