### ISSUE TITLE
within does not stop test execution

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#278]
I am attempting to test a function that processes part of `infiniteList`. I would like to have a time limit on this because it sometimes tries to consume the whole list. `within` does not seem to stop execution of a log running test. Is there a way for `within` to stop execution of a long running test?

**Comment by BebeSparkelSparkel** [comment]
`ioProperty . timeout 100` seems to stop a long running function.

**Comment by MaximilianAlgehed** [comment]
Could you provide a minimal failing example here that I can try to better understand what you mean?

**Comment by BebeSparkelSparkel** [comment]
Great question but I do not remember the problem.
