### ISSUE TITLE
Add a version of cover that makes the test fail

### ISSUE THREAD

**Issue by nh2** [nick8325/quickcheck#28]
We use `cover` to ensure that our tests are meaningful (e.g. not vacuously true due to `==>` or that cases we care about are actually generated).

Currently `cover` is only informative, so if a cover is false you get some warning printed out by `quickCheck`, but the test still passes. If you use a test runner like `test-framework`, `tasty` or `hspec`, they do not notice.

Could we have a version of `cover` that strictly lets the test fail?

This would make it possible to notice when somebody changes implementation code that lets our test cases degenerate.

**Comment by nick8325** [comment]
On reflection, I don't see how a non-strict version of `cover` would ever be useful, so I've changed it so that a failed coverage check makes the property fail.
