### ISSUE TITLE
Num instances

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#284]
Is there any reason that the following do not have Num instances?
Positive
Negative
NonZero
NonNegative
NonPositive

**Comment by phadej** [comment]
What would `negate :: Num n => Positive n -> Positive n` do?

When you write properties, unwrap early:

```haskell
myProp (Positive p) = ... with p ... 
```

**Comment by BebeSparkelSparkel** [comment]
Wish the Num class was implemented right.
