### ISSUE TITLE
Semigroup and Monoid instances for Fun

### ISSUE THREAD

**Issue by isovector** [nick8325/quickcheck#289]
It would be great to have `Semigroup` and `Monoid` instances for `Fun`.

**Comment by phadej** [comment]
I don't think that `Semigroup` for `a :-> b` is implementable. One can make unlawful instance by only applying `Monoid` to the `a -> b` parts of `Fun`, but then one could first `applyFun` and then `<>`. Can you motivate the need?

**Comment by isovector** [comment]
I think my motivation is misinformed here. I wanted to use `Fun` as a denotational model, but realized this should be an implementation detail of my property tests, not of my model. Cheers!
