### ISSUE TITLE
Arbitrary instance of Property misses exhaustive test

### ISSUE THREAD

**Issue by ndmitchell** [nick8325/quickcheck#30]
I'm pretty sure:

    instance Testable Property where
      property = property . unProperty

Should have a definition of `exhaustive`. Currently:

    Test.QuickCheck> quickCheck $ 1 == 1
    +++ OK, passed 1 tests.
    Test.QuickCheck> quickCheck $ property $ 1 == 1
    +++ OK, passed 100 tests.

I think adding the line:

    exhaustive = exhaustive . unProperty

Would do.

**Comment by nick8325** [comment]
As you noted, `exhaustive` is extremely fragile, and I don't see any way to fix it. Furthermore, it's not very useful, as lazy evaluation means that if you (e.g.) QuickCheck a `Bool`, it'll only be evaluated once.

I've now decided to remove `exhaustive` altogether. Anyone who wants to only run their property once should explicitly use the `once` combinator.

**Comment by ndmitchell** [comment]
I actually use `exhaustive` extensively in my test suite for the extra library at https://github.com/ndmitchell/extra. There it's particularly key because I generate the tests, and at the same time have `IO Bool` tests which want running only once.

That said, if removed, I could certainly figure out my own class to work on just the types I care about. Alternatively maybe executing the IO Bool stuff repeatedly doesn't actually matter. Not an attempt to persuade you to change you mind, more a note that it does turn out to be gently useful in some cases.

**Comment by nick8325** [comment]
Ah, that's awkward.

I think that the current design is far too fragile, and I've been itching to get rid of it for a while. It's probably going to go.

Now that I think about it some more, I realise we can fix the problem another way. We can add a new combinator `retest` (or some catchier name), which has the opposite effect to `once`, i.e. it tells QuickCheck that the current test case is not exhaustive. Instead of keeping track of exhaustiveness in the `Testable` class, we can make `forAll` use `retest` to indicate that it's not exhaustive. This should be a lot more robust.

**Comment by ndmitchell** [comment]
Sounds good to me - although I wonder if anyone else was relying on exhaustive? Perhaps throwing it away first, and see who complains - I'll certainly refactor its need away.

**Comment by ndmitchell** [comment]
I just benchmarked a pure Bool value, and you're right - the "running 100 times" really just evaluates it once, so there's only 0.05s between them anyway. I suspect things are different for a `Testable (IO a)` instance, but happy to consider that my fault anyway.

**Comment by nick8325** [comment]
Yes, an `IO Bool` is really the only case where this is a problem. I think @sol was also using `exhaustive`.

Anyway, I just added the `again` combinator and it was dead easy. Seems like a much cleaner solution than the previous approach, and doesn't break when you wrap your property in `property`. I'm inclined to keep it.
