### ISSUE TITLE
No instance for (RandomGen SMGen) arising from a use of ‘split’

### ISSUE THREAD

**Issue by templateK** [nick8325/quickcheck#300]
splitmix-0.1 has no instance for the `RandomGen SMGen`

**Comment by phadej** [comment]
See #299. You probably relaxed bounds of `QuickCheck` on `splitmix`, the responsibility is then on you.

**Comment by phadej** [comment]
There are revisions made on Hackage: https://hackage.haskell.org/package/QuickCheck-2.14/revisions/

**Comment by templateK** [comment]
Alright thanks for the fast response.
