### ISSUE TITLE
QuickCheck 2.7 has no instance Integral NonNegative

### ISSUE THREAD

**Issue by nh2** [nick8325/quickcheck#31]
Commit e0607bf8eb2ccd2ad12b0b4dba6e6f40fa816473 removed the `Integral` and `Real` instances for `Positive`, `NonZero` and `NonNegative`.

Two questions:

* Why were the `Real` instances removed? They only provide `toRational :: a -> Rational`, which cannot break any invariants.
* That the `Integral` instances for `Positive` and `NonZero` were removed makes sense since with `mod n n` we could create create a forbidden `0`. But for `NonNegative`, 0 is allowed. Could its `Integral` instance be reintroduced?

**Comment by nick8325** [comment]
Hi,

I removed the ```Num``` instances for these three types because they didn't work properly, see http://projects.haskell.org/pipermail/quickcheck/2014-June/000149.html.

What you should do is use pattern matching to unwrap a ```NonNegative a``` into an ```a```, so in your code it would be:
```haskell
NonNegative cpu_c <- arbitrary
NonNegative nic_c <- arbitrary
NonNegative su    <- arbitrary
```
and then you don't need to use ```fromIntegral``` or ```fromEnum``` lower down.

**Comment by nh2** [comment]
> What you should do is use pattern matching to unwrap a `NonNegative a` into an `a`

But that's not what my problem is - I used the instances for purely *constructing* these types, not destructing, and not using `arbitrary`.

I'm fine with invariant-breaking instances being removed, and only asked about those that (seemingly) are not invariant breaking - I didn't even ask about `Num` :)

**Comment by nick8325** [comment]
```Num``` is a superclass of ```Real``` and ```Integral```, though.

It would be possible to have a ```Num``` instance for ```NonNegative```, but given that none of the other modifiers support this, it would be a bit strange.

The idea with modifiers is that you should unwrap them as soon as possible, they're not supposed to be useful as values in their own right (hence the lack of instances). I didn't notice anywhere in the linked issue where unwrapping the ```NonNegative``` wouldn't work, if you point me at somewhere I can suggest how to fix it.

**Comment by nh2** [comment]
> I didn't notice anywhere in the linked issue where unwrapping the `NonNegative` wouldn't work

Ah, you're right, in [here](https://github.com/nh2/ganeti/commit/2459867d4c4aaae9d8133b3f726255c8394964a0#diff-7193d410c80f42b92ce2de5000163eb6L83) I could indeed just use

```haskell
NonNegative cpu_c <- arbitrary :: Gen (NonNegative Int)
```

and drop any `fromIntegral` or `fromEnum` - you even wrote that.

> they're not supposed to be useful as values in their own right

I guess this is the core problem: `base` doesn't give us unsigned integers, so the temptation to use QuickCheck's `NonNegative`, `Positive` and so on is high. That's what got me confused, because for that I'd really need `fromIntegral` or `fromEnum` to construct such values, outside of `Gen`s.

Thanks for taking the time :)
