### ISSUE TITLE
QuickCheck's `within` not timing out on infinite lists

### ISSUE THREAD

**Issue by tomdjong** [nick8325/quickcheck#337]
I don't understand why QuickCheck's `within` is not timing out on infinite lists. To illustrate this, consider the following MWE.

```haskell
import Test.QuickCheck

timeout :: Int
timeout = 10000

prop_length :: Property
prop_length = within timeout $ length (repeat 1) >= 0

repeat' :: a -> [a]
repeat' x = take maxBound (repeat x)

prop_length' :: Property
prop_length' = within timeout $ length (repeat' 1) >= 0
```

Now `quickCheck prop_length'` times out as expected, but `quickCheck prop_length` hangs.

Is this a bug or is there a good reason for this phenomenon?

**Comment by phadej** [comment]
`length` and `repeat` probably compile to a non-allocating loop which `base` `timeout` is not able to interrupt. 

See
- https://gitlab.haskell.org/ghc/ghc/-/issues/20209
- https://gitlab.haskell.org/ghc/ghc/-/issues/367

**Comment by tomdjong** [comment]
I see, so it's a `ghc` problem. Thanks a lot for the quick and helpful reply!
