### ISSUE TITLE
property consistently throws Test.QuickCheck.resize: negative size error

### ISSUE THREAD

**Issue by StevenXL** [nick8325/quickcheck#342]
After updating my project from [lts-19.1 ](https://www.stackage.org/lts-19.1)to [lts-19.3](https://www.stackage.org/lts-19.3), one of my spec keeps throwing a `Test.QuickCheck.resize: negative size` error:

```
  describe "MathAnswer (MathAnswer Database Representation)" $ do
    it "has coherent ToJSON / FromJSON instances" $ property $ \mathAnswer ->
      decode (encode @MathAnswer mathAnswer) `shouldBe` Just mathAnswer
```

I understand that `resize` throwing on negative size was introduced in [2015](https://github.com/nick8325/quickcheck/commit/201eed52a73640f0059e2b70a41b89088791aeea) in order to [highlight incorrect generators](https://github.com/nick8325/quickcheck/issues/45), but the test above does **not use** a custom generator. 

I've checked the list of dependencies for quickcheck and none of them [changed between the snapshots](https://rcl.freckle.com/?from=lts-19.1&to=lts-19.3) that I am using, but here is the output of [stack ls dependencies](https://gist.github.com/StevenXL/0a1a6530d6079b7e6212adf158972969).

The good news is that this does happen consistently.

**Comment by prikhi** [comment]
@StevenXL were you able to resolve this? I'm seeing the same errors with LTS 19.3

**Comment by StevenXL** [comment]
> @StevenXL were you able to resolve this? I'm seeing the same errors with LTS 19.5

Hi @prikhi. It turns out that this was a problem with the [generic-arbitrary](https://github.com/typeable/generic-arbitrary/issues/14) library, not `quickcheck` itself.
