### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by konsumlamm** [nick8325/quickcheck#351]
It's been more than two years since the last release and there have been a lot of merged PRs (e.g. #336) since then, so I think it's time for a new release.

**Comment by nick8325** [comment]
Thanks for the reminder! Yes, I should make a new release. I'll try to do it soon.

**Comment by treeowl** [comment]
Yes, please do? I'm getting a slew of incomplete pattern warnings, and they're pretty annoying.

**Comment by nick8325** [comment]
Done!
