### ISSUE TITLE
`Natural` data type: Moving instances from quickcheck-instances to QuickCheck

### ISSUE THREAD

**Issue by asr** [nick8325/quickcheck#358]
Since [`Natural`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Numeric-Natural.html) data type is defined in the `base` library, I suggest to move the instances of `Arbitrary`, `CoArbitrary` and `Function` for `Natural` from the [quickcheck-instances](https://hackage.haskell.org/package/quickcheck-instances) library to QuickCheck. In this way, we shall avoid to install the additional dependencies of `quickcheck-instances` when using QuickCheck with this data type. The instances are defined [here](https://github.com/haskellari/qc-instances/blob/master/src/Test/QuickCheck/Instances/Natural.hs#L19-L27).

@nick8325 and @phadej, any opinion?

**Comment by phadej** [comment]
`Natural` is not in `base` for all versions of `base` `QuickCheck` compiles with.

Current solution avoids code duplication (first in `QuickCheck` and then in `quickcheck-instances` for the rest of supported `base` versions).

If `QuickCheck`'s `base` lower bound is bumped to a version with `Natural`, then the instance can be moved.

**Comment by asr** [comment]
You are right. `QuickCheck` shouldn't remove the support for GHC < 7.10 (i.e. `base 4.8.0.0`) *only* because the missing instances for `Natural` were added. Thanks.
