### ISSUE TITLE
2.14.3 breaks test suite of multiple projects

### ISSUE THREAD

**Issue by felixonmars** [nick8325/quickcheck#359]
I have reported several test failures with the update to QuickCheck 2.14.3:

- https://github.com/corsis/clock/issues/87
- https://github.com/haskell/math-functions/issues/73
- https://github.com/haskell/statistics/issues/205

I am not familiar with this, but probably [this commit](https://github.com/nick8325/quickcheck/commit/07942642d7987b073a107863b68ac2f75013076b) is related?

**Comment by phadej** [comment]
Doesn't all three of these properties are broken (or at least unprecise) which is revealed by better combinator?

**Comment by felixonmars** [comment]
I agree. I opened this issue because one of the upstreams asked. Looks like there is nothing to be done here. Closing and sorry for the noise!

**Comment by cdepillabout** [comment]
Here's a few more:

- https://github.com/haskell/vector/issues/460
- https://hackage.haskell.org/package/fft (not sure where the issue tracker is for this)

**Comment by sternenseemann** [comment]
All released aeson (2.*) versions are also affected, since https://github.com/haskell/aeson/pull/1028 is unreleased.
