### ISSUE TITLE
Could `classify` collect non-covered cases too?

### ISSUE THREAD

**Issue by buzden** [nick8325/quickcheck#362]
`classify` takes both condition of a label and the label itself. Currently, it discards all labels against false conditions. As a consequence, not all mentioned labels are present in the final report, but only covered onces.

We find it useful to have an ability for non-covered labels to be printed, e.g. with `0%` coverage, or in a separate list.

Moreover, technically, since the final result contains classification result as a `Map String Int`, it can hold zeros in it. Result of a single test, however, contains just a list of classes, so this would need some change, if this feature would be considered feasible.

So, the question is: is it intentional, that non-covered classes are not printed in the final result, or is it an acceptable potential change to do so? If it is acceptable, can it be the default behaviour, or should it be hidden behind some configurable flag?

**Comment by MaximilianAlgehed** [comment]
This has been annoying me for years. C.f. the linked PR.
