### ISSUE TITLE
`PropertyM`, add combinators for making working with it easier?

### ISSUE THREAD

**Issue by MangoIV** [nick8325/quickcheck#364]
having `assert` and `asswertWith` is really barebones; it would be nice if it had something that could lift anything that fails with an IO exception into an Assertion; that way one could use predefined asserters. 

Am I missing something and there is already a trivial way to do this?

Thanks in advance.

**Comment by MangoIV** [comment]
I guess this would be kinda hard to make it library agnostic; but maybe somebody has an idea?

**Comment by MaximilianAlgehed** [comment]
If an exception is raised QuickCheck should report that as a failure. e.g.;
```
$> quickCheck $ monadicIO $ (lift (ioError (userError "Boom")) >> return True:: PropertyM IO Bool)
*** Failed! Exception: 'user error (Boom)' (after 1 test):
```
So the only thing you need to implement the functionality you're requesting is `lift`.

I'm going to close this, feel free to re-open it with a clarification if I've misunderstood.
