### ISSUE TITLE
withMaxSuccess percent done incorrect

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [nick8325/quickcheck#398]
When using `withMaxSuccess 1000 ...` the % done status goes over 100% and just shows the number of tests run.

**Comment by Rewbert** [comment]
Could you give a complete example that I can run? I am a bit confused by what you mean by `% done status`. The counter that you see as you are running tests reports the number of tests run so far, not the % done status.

**Comment by BebeSparkelSparkel** [comment]
Sorry, tasty issue https://github.com/UnkindPartition/tasty/issues/402
