### ISSUE TITLE
resize should prevent negative sizes

### ISSUE THREAD

**Issue by dcoutts** [nick8325/quickcheck#45]
Negative Gen sizes cause all sorts of trouble. Probably resize should just throw an error on negative sizes to highlight incorrect generators early during development/testing.

**Comment by dcoutts** [comment]
e.g. something like:

    scaled :: (Int -> Int) -> Gen a -> Gen a
    scaled f (MkGen m) = MkGen (\r n -> m r (checkSize (f n)))
      where
        checkSize n | n < 0 = error "Test.QuickCheck.scaled: negative size"
        checkSize n         = n

**Comment by nick8325** [comment]
Good point! This is now fixed.
