### ISSUE TITLE
arbitrarySizedBoundedIntegral only returns values in small domain

### ISSUE THREAD

**Issue by jberryman** [nick8325/quickcheck#47]
I was trying to figure out why `generate (vector 100 :: Gen [Large Int])` was only giving me small domain values, and noticed that `arbitrarySizedBoundedIntegral` is incorrect:

    >  fmap maximum $ replicateM 1000000 $ generate (arbitrarySizedBoundedIntegral :: Gen Int)
    4096

That code's a bit opaque to me, sorry I'm not of much help.

**Comment by nick8325** [comment]
Hi,

That's actually because `generate` uses a fixed size of 30. If you try

```haskell
sample (resize 100 (arbitrary :: Gen (Large Int)))
```

you'll get nice big integers - QuickCheck goes up to size 100 by default during testing.

Conceivably `generate` should pick a random size, but for the time being I've documented that it uses a fixed size.

**Comment by jberryman** [comment]
Okay, thanks for the quick feedback!
