### ISSUE TITLE
quickCheckWithResult leaks exceptions when chatty is False and used with (===)

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#48]
If we have a property that uses `(===)` and fails with an exception, e.g.

```haskell
prop = (=== (undefined :: Int))
```

then `quickCheckWithResult` will leak that exception as part of the `output` when run with `chatty = False`.

Here are two GHCi sessions that demonstrate the issue.  Note that for the first case (when `chatty = True`) the `output` field is a total string.  In contrast, for the second case (when `chatty = False`) the `output` field contains an error thunk.

```
ghci> output <$> quickCheckWithResult stdArgs {chatty = True} prop
"*** Failed! Exception: 'Prelude.undefined' (after 1 test): \n0\nException thrown by generator: 'Prelude.undefined'\n"
```

```
ghci> output <$> quickCheckWithResult stdArgs {chatty = False} prop
"*** Failed! Exception: 'Prelude.undefined' (after 1 test): \n0\n0 /= *** Exception: Prelude.undefined
```

**Comment by nick8325** [comment]
Fixed now, the terminal output wasn't strict enough. Thanks!

**Comment by sol** [comment]
@nick8325 Will there be a bug fix release to Hackage?

**Comment by nick8325** [comment]
Done! 2.8.1 is now on Hackage.

**Comment by sol** [comment]
Nice! :)
