### ISSUE TITLE
quickcheck test times out, yet functions are fast when run by hand

### ISSUE THREAD

**Issue by gittywithexcitement** [nick8325/quickcheck#56]
I've got a quickcheck property that times out (5 second timeout) when the test case gets large enough. If I run that specific test case through the functions under test within GHCI, it completes instantly. Test failure is reproducible, happening after about 90 test cases every time.

You should be able to reproduce it with [this file](https://gist.github.com/gittywithexcitement/27c65759f6742babe77e). 

GHC version:
```
> ghc -v
Glasgow Haskell Compiler, Version 7.10.1, stage 2 booted by GHC version 7.8.4
```

If you want a cabal file, here's a chunk:
```
test-suite test
  default-language:
    Haskell2010
  type:
    exitcode-stdio-1.0
  hs-source-dirs:
    Test
  main-is:
    test.hs
  default-extensions: 
  build-depends:
      base >= 4.8
    , QuickCheck
    , bytestring
```

----

An example failure is
```
*** Failed! Exception: '<<timeout>>' (after 90 tests):  
Large {getLarge = 69071890884779960}
```
When I pass it through GHCI, it completes instantly, whereas QuickCheck says the test times out, taking >= 5 seconds.
```
> fromSignedByteString . toSignedByteString $ 69071890884779960
69071890884779960
```

It makes no progress if I remove the timeout and just let it run

```
> time dist/build/test/test
^C*** Failed! Exception: 'user interrupt' (after 94 tests): 
Large {getLarge = 102007353455633744}
182.37user
```

Memory usage doesn't climb, so it doesn't seem to be a large space leak.

Since I can't reproduce the problem when running my functions outside of quickcheck, I'm assuming that quickcheck is the problem.

**Comment by nick8325** [comment]
Hi,

It's because your property uses `Int64`, but when running the test case by hand you're using `Integer`. When I explicitly use `Int64` it loops in GHCi too:

```haskell
fromSignedByteString (toSignedByteString (69071890884779960 :: Int64))
```

So the loop is in your code somewhere. Not sure where though!

**Comment by gittywithexcitement** [comment]
doh! Thanks.
