### ISSUE TITLE
Arbitrary instances for containers types

### ISSUE THREAD

**Issue by phadej** [nick8325/quickcheck#62]
QuickCheck depends on containers, could the Arbitrary instances for it be added?

Naive `Map` generation might not be what you want, but it's still better then no instance. `Set` and `Seq` should be trivial.

I can write a PR, if the idea is ok.

**Comment by idupree** [comment]
I'm also interested in this. I currently have an orphan Map instance in my own project.

**Comment by phadej** [comment]
@idupree for now check http://hackage.haskell.org/package/quickcheck-instances

**Comment by nick8325** [comment]
Container instances are in the latest git HEAD now. Sorry for the delay!
