### ISSUE TITLE
Extraneous check in Positive newtype

### ISSUE THREAD

**Issue by expipiplus1** [nick8325/quickcheck#65]
In the instance for `Arbitrary (Positive a)` the definition for arbitrary is this:
```
arbitrary =
    ((Positive . abs) `fmap` (arbitrary `suchThat` (/= 0))) `suchThat` gt0
    where gt0 (Positive x) = x > 0
```

Is the check `` `suchThat` gt0 `` just in case the `Num` instance for `a` has a misbehaving definition for `abs`?

**Comment by nick8325** [comment]
Yes, for example `Int` misbehaves :)

```haskell
Prelude> abs (minBound :: Int)
-9223372036854775808
```

I think that before we added this check `Positive Int8` would sometimes generate -128.

**Comment by expipiplus1** [comment]
Cool beans, just wanted to make sure :)
