### ISSUE TITLE
Please add support for GHC 8.0.1 release candidate

### ISSUE THREAD

**Issue by peti** [nick8325/quickcheck#71]
The new release candidate for GHC 8.x cannot compile QuickCheck because of the following restrictions on `template-haskell`:

> template-haskell >=2.4 && <2.11

This issue prevents of from building (or rather: testing) pretty much any significant package with that compiler. Would it be possible to get an update for QuickCheck that support the 8.x series of GHC?

**Comment by nick8325** [comment]
Hi,

I released version 2.8.2 earlier today which builds just fine with the GHC 8 RC on my machine. What problem do you get on yours? There's no upper bound on the `template-haskell` package in the cabal file as far as I can see.

**Comment by peti** [comment]
You are right, `QuickCheck-2.8.2` works like a charm. Thank you very much for the quick response!
