### ISSUE TITLE
Drop support for GHC <7

### ISSUE THREAD

**Issue by phadej** [nick8325/quickcheck#74]
I tried to make a matrix with GHC 6.12.3, and it starts to be quite troublesome to compile. Maybe one could get further by disabling tests, but then `tested-with` would lie.

Particularly, seems that I broke `binary-0.8` for GHC <7.0 (because it isn't tested)

*EDIT* this would highly simplify cabal file too.

**Comment by hvr** [comment]
Unless there's actually somebody using or testing latest QuickCheck with GHCs prior to 7.0, I second this. 

GHC 7.0 (which was released in 2010) is most likely the oldest GHC you can expect on Linux distribution which are not yet EOL'ed (with "enterprise" distros being the ones we need to worry about most).

see also https://github.com/haskell/cabal/issues/3108#issuecomment-180064508

**Comment by phadej** [comment]
Thanks. I'll update my other pull request during today.
