### ISSUE TITLE
Break Arbitrary out into another package

### ISSUE THREAD

**Issue by timmytofu** [nick8325/quickcheck#77]
To make `Arbitrary` instances for my types I have to include quickcheck in my main library depends, rather than just testing, or deal with orphaned instance warnings by defining it in the test code only (and then I can't put properties in doctest, as well, I think).

**Comment by phadej** [comment]
@timmytofu why it's problematic to depend on `QuickCheck` directly? This package has very light dependencies anyway?

**Comment by nick8325** [comment]
Hi,

I don't see how this would help. Wouldn't your library then have to depend on the `quickcheck-arbitrary` (or whatever) package instead? Having orphan instances is of course unfortunate but I think it's the best approach here.
