### ISSUE TITLE
Add Arbitrary instance for Text

### ISSUE THREAD

**Issue by seagreen** [nick8325/quickcheck#80]
How would we feel about adding the `text` package as a dependency of QuickCheck? I know it's good to keep QuickCheck's dependencies light, but I think depending on Haskell's recommended string type is a reasonable measure.

Right now there's probably an orphan `Arbitrary Text` instance in pretty much every sizable application that uses QuickCheck (and library authors have it even worse because they don't get that option).

**Comment by phadej** [comment]
FYI: http://hackage.haskell.org/package/quickcheck-instances

**Comment by nick8325** [comment]
Hi,

I try to provide instances only for types in `base` (and now also `containers` because QuickCheck depends on it). I'm not very keen on adding more dependencies to QuickCheck but it does make some sense for `text`. All the same I don't think I'm willing to do this just yet.

As @phadej says there's `quickcheck-instances` which provides most of the missing stuff, which I suppose is what people should be using for now. Maybe it would be a good idea for us to recommend `quickcheck-instances` and e.g. put a link to it in the QuickCheck documentation?

**Comment by seagreen** [comment]
`quickcheck-instances` is great for applications, but I'm hesitant to use it in a library because it contains only orphan instances by definition.

You would think just writing `arbitraryText = T.pack <$> arbitrary` would be good enough, but even in a tiny library the complexity of your Arbitrary instances starts to go up quickly this way, since (at least in my case) `Text` gets used a lot.

I definitely respect not wanting to add more dependencies to `quickcheck` though. I don't think there's really a right answer here:(

**Comment by seagreen** [comment]
Perhaps I'm being too quick to dismiss `quickcheck-instances`. Do you guys think it's appropriate for library use?

**Comment by phadej** [comment]
Valid concern. Not many libraries expose `Arbitrary` instances, so even (reverse dependencies of `quickcheck-instances`)[http://packdeps.haskellers.com/reverse/quickcheck-instances] shows many packages using it; not many are even depending on `QuickCheck`. Yet IMHO `quickcheck-instances` is go for package for `QuickCheck` instances, as other packages tests (which shouldn't fail) depend on it anyway (either directly or thru your package - it's irrelevant).

**Comment by seagreen** [comment]
Thanks for the info! Being able to use `quickcheck-instances` removes the pressure that made me need `Arbitrary Text` in `quickcheck`. Perhaps it would still be a good idea at some point, but as far as I'm concerned feel free to close this.

**Comment by saurabhnanda** [comment]
If QC already depends on text due to #118 any chance of reconsidering this decision? Isnt Text a given for any non-trivial project nowadays?

**Comment by nick8325** [comment]
We've decided to go the other way in #158 and make QuickCheck have a minimal set of dependencies.

This means that `text` could, in principle, safely define an `Arbitrary` instance (though I don't know if they'd want to). For now, such instances are in `quickcheck-instances`.

**Comment by saurabhnanda** [comment]
Is there any way to make this a data-backed decision? Would it be easy to pull out a list of all packages from Hackage that: 

* depend on Quickcheck but not on Text
* depend on Quickcheck and also on Text

Btw, how bad are orphan instances, really?

**Comment by nick8325** [comment]
I don't know any way of getting transitive dependencies out of Cabal, unfortunately. Looking at http://packdeps.haskellers.com/reverse/QuickCheck, there seem to be plenty of library packages which don't depend on text (it's more the case that some kinds of packages depend on text and others don't).

The problem with orphan instances is that they leak - i.e. if module A imports module B, and module B imports module C which defines an orphan instance, then module A gets the orphan instance too even though it didn't ask for it. If module B is part of a library and you are writing module A, you may be unhappy about this, so library authors are wary of relying on orphan instances. I don't think it's a problem to use them in code which is never used by outside packages (e.g., a test suite or executable).
