### ISSUE TITLE
Add an Alternative instance for Gen

### ISSUE THREAD

**Issue by dalaing** [nick8325/quickcheck#87]
I'm wondering if it would be possible to add an `Alternative` instance for `Gen`

The starting point for the change would be to move from:
`newtype Gen a = MkGen { unGen :: QCGen -> Int -> a }`
to either:
`newtype Gen a = MkGen { unGen :: QCGen -> Int -> Maybe a }`
or:
`newtype Gen a = MkGen { unGen :: QCGen -> Int -> [a] }`

I think the version with the list for the results would probably work better for `<|>`, with something like `oneof` being used to get back to a single value - like the current behaviour - when the list is non-empty.

While making a breaking change like that, I'd also be tempted to add another `Int` parameter in there, to be used to make `<|>` behave more like `frequency`, with corresponding helpers like `sized` / `resize` to help out.

I'm keen to give this a go myself and see how far I can push it, but I thought I'd put something here and so whether folks are strongly for or strongly against the idea, or if there are any landmines here I should be aware of,  before I put too much time into it.

**Comment by reiddraper** [comment]
I tend to think that a generator that "sometimes can't produce a value" is a big code-smell, typically by overzealous use of `suchThat`. I don't see the appeal of having that idea baked into the core of QuickCheck.

**Comment by dalaing** [comment]
I agree with it being a code smell in that case - and most of the other existing cases that I can think of.

I should probably step back a little and explain why I'm after an Alternative instance :)

I've been playing with the `Divisible` and `Decidable` from `contravariant`, and it looks like with some higher order versions of those, combined with `Applicative` and `Alternative` respectively, you can build some interesting functionality around the composition of functions for shrinking, and around the combination of `Gen`s and functions for shrinking.

I can probably get by without the various units from those typeclasses, and use `Apply` and `Alt` from semigroupoids, but having a list of values inside `Gen` might still have been handy for making the `Alt` instances a bit fairer about which branches it takes.

I've got plenty to play with before that idea is ready to put through some serious review, but I figured adding `Alternative` for `Gen` would be a good warmup.  If it's not something people want in QuickCheck, that's OK with me.

**Comment by dalaing** [comment]
Closing this now - it seems that `hedgehog` is doing what I was trying to do when I filled this.
