### ISSUE TITLE
Add Arbitrary instance for arrays

### ISSUE THREAD

**Issue by treeowl** [nick8325/quickcheck#88]
This package depends on `array` transitively, via `containers`, so adding it as a direct dependency can't do any harm.

**Comment by phadej** [comment]
http://hackage.haskell.org/package/quickcheck-instances defines `array` instances. Ping @aslatter if `array` instances are moved into `QuickCheck` package.

**Comment by nick8325** [comment]
I slightly worry about how to choose the array bounds (i.e., should the indexing always start from 0, should it start from a small integer, or can it start from any integer?)

I think we can use the existing modifiers to control this, so if someone asks for an `Array Int a` they get small indices but if they ask for an `Array (Large Int) a` they get large indices (but the size of the array will be unaffected).

**Comment by nick8325** [comment]
Pinging @aslatter, these will be in QuickCheck 2.10.
