### ISSUE TITLE
QC only visit part of search space for Word64

### ISSUE THREAD

**Issue by Shimuuar** [nick8325/quickcheck#92]
Recently I found out QC never finds counterexample to following property even after 1e8 test cases:

````.haskell
p_failing :: Word64 -> Bool
p_failing i = testBit i 63 == False
````

But it's false for exactly half of `Word64`!  Then plotted frequency for each bit of Word64 which is passed to property (1e6 test cases). Bits 63 and 62 are always zero in all test cases. 
![bit_freq](https://cloud.githubusercontent.com/assets/100394/14858818/9ab926c0-0cb2-11e6-88cf-9e74a55d2636.png)

And looking at consecutive inputs reveals strange pattern: 

```
     1  0x0000000000000001
     2  0x0000000000000000
     3  0x0000000000000001
     4  0x0000000000000000
     5  0x0000000000000002
     6  0x0000000000000004
     7  0x0000000000000005
     8  0x000000000000000b
     9  0x000000000000000c
    10  0x0000000000000009
....
    90  0x004fe9b98bdd482e
    91  0x00bf83bfb1a60c70
    92  0x00a8e49cc9fee6ca
    93  0x00385b6297fbde9d
    94  0x007069be7a8569e9
    95  0x06f7323a8211c169
    96  0x05668182d04237f2
    97  0x0ebac5a91be8d419
    98  0x134527f8393c2980
    99  0x1f2b0200977d9706
   100  0x3a1ce8ef8c3eac26
   101  0x0000000000000000
   102  0x0000000000000000
   103  0x0000000000000000
   104  0x0000000000000000
   105  0x0000000000000004
```

Every 100 of test cases generator starts to explore search space from small numbers again and never reaches big Word64

**Comment by nick8325** [comment]
Thanks for the bug report! This was an off-by-one error in `arbitrarySizedBoundedIntegral` and is now fixed.

By the way, the strange pattern you report is because QuickCheck resets the size parameter every 100 test cases, and starts generating small values again - this is normal behaviour, and not related to the bug you saw.
