### ISSUE TITLE
Add Arbitrary instance for QCGen

### ISSUE THREAD

**Issue by treeowl** [nick8325/quickcheck#94]
I think this is probably sensible:

``` haskell
instance Arbitrary QCGen where
  arbitrary = MkGen (\g _ -> g)
```

Zemyla (jokingly?) suggested also making it an instance of `CoArbitrary` so that `Gen` can also be made an instance of `Arbitrary`. Why not?

``` haskell
instance CoArbitrary QCGen where
  coarbitrary s = variant (fst (next s))
```

With this in place, a property can ask for a generator and do with it what it likes.

**Comment by nick8325** [comment]
The `Arbitrary` instance seems sensible enough. The `CoArbitrary` instance is incorrect though as the generated function will only depend on the _first_ value returned by the `QCGen`. I'll add the `Arbitrary` instance and leave out `CoArbitrary` until someone actually wants it.

**Comment by kindaro** [comment]
Wow this actually lets me extract the random seed from a running generator? Extra fancy!

**Comment by phadej** [comment]
@kindaro

> Wow this actually lets me extract the random seed from a running generator?

Not really. note the `split` in https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/src/Test.QuickCheck.Gen.html#line-76, so you cannot just peek at the generator without changing it.

This is why the 

```haskell
instance Arbitrary QCGen where
  arbitrary = MkGen (\g _ -> g)
```

instance works (and `Arbitrary`) in general. We don't need to worry about updating state
