### ISSUE TITLE
Add Function instances for more types

### ISSUE THREAD

**Issue by treeowl** [nick8325/quickcheck#97]
The following are particularly notably missing: `Word`, `Word16`, `Word32`, `Word64`, `Int8`, `Int16`, `Int32`, `Int64`, `Natural`, `Complex`, `Data.Sequence.Seq`, `Data.IntMap.IntMap`, `Data.Set.Set`, `Data.IntSet.IntSet`, `Data.Tree.Tree`, `Data.Array.Array`, `Data.Array.Unboxed.UArray`, `Text.PrettyPrint.Doc`, `Text.PrettyPrint.Annotated.Doc`.

**Comment by nick8325** [comment]
Noted. Really there should be a `Function` instead for any type which has a `CoArbitrary` instance, as well as generics support. I'll fix it when I have a bit of time.

**Comment by nick8325** [comment]
s/instead/instance/

**Comment by treeowl** [comment]
It's possible I'll get around to it first; we'll see. Right now I'm chasing
down a crazy GMP error that may or may not be QuickCheck related.
