### ISSUE TITLE
Please specify package version bounds for dependencies

### ISSUE THREAD

**Issue by mrkkrp** [nick8325/quickcheck#99]
Quick Check 2.8.2 does not work with *any* `template-haskell`. In particular, it does not work with version 2.11. Please take time and specify package version bounds.

**Comment by phadej** [comment]
Could you elaborate? What doesn't work? http://matrix.hackage.haskell.org/package/QuickCheck and travis say `QuickCheck` is green.

**Comment by mrkkrp** [comment]
https://travis-ci.org/stackbuilders/stache/jobs/141392203#L326

**Comment by nick8325** [comment]
OK, it seems that Cabal is installing a newer version of `template-haskell` than the one shipped with GHC?!

I had no idea that was possible, I thought `template-haskell` was a wired-in package.

In that case the CPP macros in `Test/QuickCheck/All.hs` are wrong. They check the version of GHC and they need  to check the `template-haskell` version instead. I will push a patch ASAP.
